image: docker:latest
services: 
  - docker:dind

variables: 
  DOCKER_DRIVE: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
stages:
  - build
  - package

maven-build:
  image: maven:3.6.0-jdk-11
  stage: build
  tags: 
    - docker
  script: 
    -  mvn install:install-file -Dfile=/builds/gitlab/unicef/yum-hvs-web/mis-web/src/lib/barcelona-theme-2.0.0.jar -DgroupId=barcelona-theme-2.0.0.jar -DartifactId=barcelona-theme-2.0.0 -Dversion=2 -Dpackaging=jar -DgeneratePom=false
    -  mvn clean install
  only:
    - tags
  cache:
    key: ${CI_COMMIT_REF_SLUG}      
    paths:
      - ./.m2/repository
  artifacts:
    paths:
      - ./mis-web/target/*.jar
      
docker-build:
  stage: package
  tags: 
    - docker
  script: 
    - echo -n $AZURE_ACR_PASSWORD | docker login --username $Azure_User --password-stdin $AZURE_ACR_URL
    - docker build -t $BUILD_IMAGE .
    - docker tag $BUILD_IMAGE $AZURE_ACR_URL/$BUILD_IMAGE
    - docker push $AZURE_ACR_URL/$BUILD_IMAGE
  only: 
    - tags

